# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz_trabajo_final1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(767, 569)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Downloads/Graficos/e2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 771, 571))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("background-color: rgb(42, 56, 56);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(40, 30, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Forte")
        font.setPointSize(36)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: white;")
        self.label_12.setObjectName("label_12")
        self.tbl_lista = QtWidgets.QTableWidget(self.tab_3)
        self.tbl_lista.setGeometry(QtCore.QRect(80, 130, 611, 381))
        self.tbl_lista.setStyleSheet("QWidget {\n"
"    background-color: rgb(80, 95, 149);\n"
"    color: #fffff8;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(80, 95, 149);\n"
"    padding: 2px;\n"
"    border: 1px solid #fffff8;\n"
"    font-size: 9pt;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    gridline-color: #fffff8;\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: #646464;\n"
"    border: 1px solid #fffff8;\n"
"}")
        self.tbl_lista.setObjectName("tbl_lista")
        self.tbl_lista.setColumnCount(6)
        self.tbl_lista.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setKerning(True)
        item.setFont(font)
        self.tbl_lista.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_lista.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_lista.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_lista.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_lista.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_lista.setHorizontalHeaderItem(5, item)
        self.btn_cargar = QtWidgets.QPushButton(self.tab_3)
        self.btn_cargar.setGeometry(QtCore.QRect(520, 90, 161, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_cargar.setFont(font)
        self.btn_cargar.setStyleSheet("background-color: rgb(108, 100, 162);\n"
"color: white;\n"
"border-radius: 10px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("iconos/cargar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cargar.setIcon(icon1)
        self.btn_cargar.setObjectName("btn_cargar")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(210, 150, 141, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: white;")
        self.label_7.setObjectName("label_7")
        self.line_fec = QtWidgets.QLineEdit(self.tab)
        self.line_fec.setGeometry(QtCore.QRect(360, 189, 113, 31))
        self.line_fec.setStyleSheet("QLineEdit {\n"
"    border: 2px solid black; /* Borde*/\n"
"    border-radius: 5px; /* Esquinas redondeadas */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    background-color: #f2f2f2; /* Fondo gris claro */\n"
"    color: #333; /* Color del texto */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #45a049; /* Cambio de color del borde al obtener el foco */\n"
"}\n"
"")
        self.line_fec.setObjectName("line_fec")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(240, 200, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: white;")
        self.label_9.setObjectName("label_9")
        self.line_nom = QtWidgets.QLineEdit(self.tab)
        self.line_nom.setGeometry(QtCore.QRect(360, 139, 201, 31))
        self.line_nom.setStyleSheet("QLineEdit {\n"
"    border: 2px solid black; /* Borde*/\n"
"    border-radius: 5px; /* Esquinas redondeadas */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    background-color: #f2f2f2; /* Fondo gris claro */\n"
"    color: #333; /* Color del texto */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #45a049; /* Cambio de color del borde al obtener el foco */\n"
"}\n"
"")
        self.line_nom.setObjectName("line_nom")
        self.btn_ven = QtWidgets.QPushButton(self.tab)
        self.btn_ven.setGeometry(QtCore.QRect(280, 250, 231, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_ven.setFont(font)
        self.btn_ven.setStyleSheet("background-color: rgb(0, 198, 145);\n"
"color: white;\n"
"border-radius: 10px;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("iconos/agregar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ven.setIcon(icon2)
        self.btn_ven.setObjectName("btn_ven")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(40, 30, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Forte")
        font.setPointSize(36)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: white;")
        self.label_13.setObjectName("label_13")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.line_id_venta = QtWidgets.QLineEdit(self.tab_2)
        self.line_id_venta.setGeometry(QtCore.QRect(350, 70, 231, 31))
        self.line_id_venta.setStyleSheet("QLineEdit {\n"
"    border: 2px solid black; /* Borde*/\n"
"    border-radius: 5px; /* Esquinas redondeadas */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    background-color: #f2f2f2; /* Fondo gris claro */\n"
"    color: #333; /* Color del texto */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #45a049; /* Cambio de color del borde al obtener el foco */\n"
"}\n"
"")
        self.line_id_venta.setObjectName("line_id_venta")
        self.btn_buscar = QtWidgets.QPushButton(self.tab_2)
        self.btn_buscar.setGeometry(QtCore.QRect(640, 50, 81, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_buscar.setFont(font)
        self.btn_buscar.setStyleSheet("background-color: rgb(108, 100, 162);\n"
"color: white;\n"
"border-radius: 10px;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("iconos/buscar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_buscar.setIcon(icon3)
        self.btn_buscar.setObjectName("btn_buscar")
        self.tbl_venta = QtWidgets.QTableWidget(self.tab_2)
        self.tbl_venta.setGeometry(QtCore.QRect(80, 130, 611, 81))
        self.tbl_venta.setStyleSheet("QWidget {\n"
"    background-color: rgb(80, 95, 149);\n"
"    color: #fffff8;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(80, 95, 149);\n"
"    padding: 2px;\n"
"    border: 1px solid #fffff8;\n"
"    font-size: 9pt;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    gridline-color: #fffff8;\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: #646464;\n"
"    border: 1px solid #fffff8;\n"
"}")
        self.tbl_venta.setObjectName("tbl_venta")
        self.tbl_venta.setColumnCount(6)
        self.tbl_venta.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setKerning(True)
        item.setFont(font)
        self.tbl_venta.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_venta.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_venta.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_venta.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_venta.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_venta.setHorizontalHeaderItem(5, item)
        self.tbl_detalles = QtWidgets.QTableWidget(self.tab_2)
        self.tbl_detalles.setGeometry(QtCore.QRect(80, 250, 611, 261))
        self.tbl_detalles.setStyleSheet("QWidget {\n"
"    background-color: rgb(80, 95, 149);\n"
"    color: #fffff8;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(80, 95, 149);\n"
"    padding: 2px;\n"
"    border: 1px solid #fffff8;\n"
"    font-size: 9pt;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    gridline-color: #fffff8;\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: #646464;\n"
"    border: 1px solid #fffff8;\n"
"}")
        self.tbl_detalles.setObjectName("tbl_detalles")
        self.tbl_detalles.setColumnCount(6)
        self.tbl_detalles.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_detalles.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_detalles.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_detalles.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_detalles.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_detalles.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_detalles.setHorizontalHeaderItem(5, item)
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(60, 110, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(60, 230, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(400, 40, 121, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white;")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(50, 30, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Forte")
        font.setPointSize(36)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: white;")
        self.label_15.setObjectName("label_15")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Registro de Productos"))
        self.label_12.setText(_translate("Form", "Ventas:"))
        item = self.tbl_lista.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Codigo"))
        item = self.tbl_lista.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Comprador Nombre"))
        item = self.tbl_lista.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Venta Fecha"))
        item = self.tbl_lista.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Venta Monto"))
        item = self.tbl_lista.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Venta IGV"))
        item = self.tbl_lista.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Venta Monto Final"))
        self.btn_cargar.setText(_translate("Form", "Cargar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Listar Venta"))
        self.label_7.setText(_translate("Form", "Nombre del comprador:"))
        self.label_9.setText(_translate("Form", "Fecha de la venta:"))
        self.btn_ven.setText(_translate("Form", "Agregar venta e insertar detalles"))
        self.label_13.setText(_translate("Form", "Agregar Venta:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Agregar Venta"))
        self.btn_buscar.setText(_translate("Form", "Buscar"))
        item = self.tbl_venta.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Codigo"))
        item = self.tbl_venta.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Comprador Nombre"))
        item = self.tbl_venta.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Venta Fecha"))
        item = self.tbl_venta.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Venta Monto"))
        item = self.tbl_venta.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Venta IGV"))
        item = self.tbl_venta.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Venta Monto Final"))
        item = self.tbl_detalles.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Codigo_venta"))
        item = self.tbl_detalles.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Producto_id"))
        item = self.tbl_detalles.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Producto_nombre"))
        item = self.tbl_detalles.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Producto_precio"))
        item = self.tbl_detalles.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Producto_cantidad"))
        item = self.tbl_detalles.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Producto_Total"))
        self.label.setText(_translate("Form", "Venta:"))
        self.label_2.setText(_translate("Form", "Detalles de la venta:"))
        self.label_3.setText(_translate("Form", "Ingrese id de venta:"))
        self.label_15.setText(_translate("Form", "Busqueda:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Buscar Venta"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
